// ═══════════════ HEAT PUMP SIZE CALCULATOR ═══════════════
// Self-contained: no dependency on the main app (index.html). Loads its own
// trimmed residential product dataset (calc-products.json, generated by
// build.py) for the "heat pumps that could cover this" recommendations.
//
// Method: whole-dwelling fabric + ventilation heat loss following the CIBSE
// Domestic Heating Design Guide approach — fabric heat loss (Σ area×U-value)
// + ventilation heat loss (0.33 × ACH × volume), both × design temperature
// difference for peak kW; annual kWh via the standard degree-day method
// (heat loss coefficient × HDD × 24). Envelope areas are estimated from
// floor area/storeys/property shape, not measured room by room — this is a
// whole-dwelling estimate, not a full BS EN 12831 survey.
const DEMAND_AGE_BANDS=[
  {id:'pre1930',label:'Before 1930',wallU:1.7,roofU:1.5,floorU:1.0,ach:1.0},
  {id:'1930-1966',label:'1930–1966',wallU:1.5,roofU:0.9,floorU:1.0,ach:0.85},
  {id:'1967-1990',label:'1967–1990',wallU:0.9,roofU:0.35,floorU:0.6,ach:0.7},
  {id:'1991-2002',label:'1991–2002',wallU:0.45,roofU:0.25,floorU:0.4,ach:0.6},
  {id:'2003-2011',label:'2003–2011',wallU:0.30,roofU:0.16,floorU:0.25,ach:0.5},
  {id:'2012+',label:'2012 onwards',wallU:0.18,roofU:0.13,floorU:0.13,ach:0.45}
];
const DEMAND_PROPERTY_TYPES=[
  {id:'detached',label:'Detached house',exposedFrac:1.0,shapeFactor:1.15,doors:2},
  {id:'semi',label:'Semi-detached house',exposedFrac:0.75,shapeFactor:1.05,doors:2},
  {id:'endterrace',label:'End-terrace house',exposedFrac:0.75,shapeFactor:1.0,doors:2},
  {id:'midterrace',label:'Mid-terrace house',exposedFrac:0.5,shapeFactor:0.9,doors:1},
  {id:'bungalow',label:'Bungalow',exposedFrac:1.0,shapeFactor:1.1,doors:2},
  {id:'flat',label:'Flat / apartment',exposedFrac:0.35,shapeFactor:0.85,doors:1}
];
const DEMAND_GLAZING=[
  {id:'single',label:'Single glazed',u:4.8},
  {id:'double-old',label:'Double glazed (older)',u:2.8},
  {id:'double-modern',label:'Double glazed (modern, low-E)',u:1.6},
  {id:'triple',label:'Triple glazed',u:1.0}
];
const DEMAND_VENTILATION=[
  {id:'natural',label:'Natural / extract fans only',achMult:1.0},
  {id:'mvhr',label:'MVHR (mechanical heat recovery)',achMult:0.55}
];
// Indicative regional design temperature (°C) and annual heating degree
// days (base 15.5°C), consistent with the range historically published by
// CIBSE (roughly -2°C to -5°C across the UK) and MET Office-derived HDD
// data (~1,900 in London to ~2,650 in the north of Scotland). These are
// planning-level regional figures, not exact site-specific CIBSE Guide A
// Table 2.5 values matched to a postcode — a full MCS survey uses those.
const DEMAND_REGIONS=[
  {id:'london',label:'Greater London',designTemp:-3,hdd:1900},
  {id:'se',label:'South East England',designTemp:-3,hdd:2000},
  {id:'sw',label:'South West England',designTemp:-2,hdd:1950},
  {id:'east',label:'East of England',designTemp:-3,hdd:2050},
  {id:'emid',label:'East Midlands',designTemp:-4,hdd:2200},
  {id:'wmid',label:'West Midlands',designTemp:-4,hdd:2200},
  {id:'yorks',label:'Yorkshire & the Humber',designTemp:-4,hdd:2300},
  {id:'nw',label:'North West England',designTemp:-3.5,hdd:2250},
  {id:'ne',label:'North East England',designTemp:-4,hdd:2400},
  {id:'wales',label:'Wales',designTemp:-3.5,hdd:2200},
  {id:'scotcentral',label:'Scotland (Central & South)',designTemp:-4.5,hdd:2450},
  {id:'scotnorth',label:'Scotland (North & Highlands)',designTemp:-5,hdd:2650},
  {id:'ni',label:'Northern Ireland',designTemp:-3.5,hdd:2300}
];
const DEMAND_UK_AVERAGE_REGION={label:'UK average',designTemp:-3,hdd:2050};
let demandState={mode:'simple'};
let calcDb=[];

function demandEstimateGeometry(floorArea,storeys,ptype){
  const pt=DEMAND_PROPERTY_TYPES.find(p=>p.id===ptype)||DEMAND_PROPERTY_TYPES[0];
  const footprint=floorArea/storeys;
  const side=Math.sqrt(Math.max(footprint,1));
  const perimeter=4*side*pt.exposedFrac;
  const storeyHeight=2.4;
  const grossWallArea=perimeter*storeyHeight*storeys;
  const windowArea=grossWallArea*0.15;
  const doorArea=pt.doors*1.85;
  const netWallArea=Math.max(grossWallArea-windowArea-doorArea,0);
  const isFlat=ptype==='flat';
  const roofArea=isFlat?0:footprint;
  const groundFloorArea=isFlat?0:footprint;
  const volume=floorArea*storeyHeight;
  return {netWallArea,windowArea,doorArea,roofArea,groundFloorArea,volume,shapeFactor:pt.shapeFactor};
}

function demandCompute(inp){
  const age=DEMAND_AGE_BANDS.find(a=>a.id===inp.ageband)||DEMAND_AGE_BANDS[2];
  const geo=demandEstimateGeometry(inp.floorArea,inp.storeys,inp.ptype);
  const glazing=DEMAND_GLAZING.find(g=>g.id===inp.glazing)||DEMAND_GLAZING[2];
  const vent=DEMAND_VENTILATION.find(v=>v.id===inp.ventilation)||DEMAND_VENTILATION[0];
  const region=inp.mode==='simple'?DEMAND_UK_AVERAGE_REGION:(DEMAND_REGIONS.find(r=>r.id===inp.region)||DEMAND_REGIONS[0]);
  const wallU=inp.wallUpgrade?Math.min(age.wallU,0.30):age.wallU;
  const roofU=inp.roofUpgrade?Math.min(age.roofU,0.16):age.roofU;
  const floorU=age.floorU;
  const doorU=3.0;
  const fabricUA=geo.netWallArea*wallU+geo.windowArea*glazing.u+geo.doorArea*doorU+geo.roofArea*roofU+geo.groundFloorArea*floorU;
  const ach=age.ach*vent.achMult;
  const ventUA=0.33*ach*geo.volume;
  let totalUA=(fabricUA+ventUA)*geo.shapeFactor;
  if(inp.extraInsulationHigh)totalUA*=0.85;
  const dT=inp.internalTemp-region.designTemp;
  const marginMult=1+(inp.margin||0)/100;
  const peakLossKW=Math.max(totalUA*dT*marginMult/1000,0);
  const annualKWh=Math.max(totalUA*region.hdd*24/1000,0);
  return {peakLossKW,annualKWh,totalUA,dT,region,geo,wallU,roofU,floorU,glazing,ach};
}

function demandGatherInputs(){
  const g=id=>document.getElementById(id);
  if(demandState.mode==='simple'){
    const ptype=g('dm-s-ptype').value;
    const insulation=g('dm-s-insulation').value;
    return {
      mode:'simple',
      floorArea:parseFloat(g('dm-s-floorarea').value)||0,
      ptype, ageband:g('dm-s-ageband').value,
      storeys:(ptype==='bungalow'||ptype==='flat')?1:2,
      region:null, glazing:'double-modern', ventilation:'natural',
      wallUpgrade: insulation!=='asbuilt', roofUpgrade: insulation!=='asbuilt',
      extraInsulationHigh: insulation==='high',
      internalTemp:21, margin:10
    };
  }
  return {
    mode:'detailed',
    floorArea:parseFloat(g('dm-d-floorarea').value)||0,
    ptype:g('dm-d-ptype').value,
    ageband:g('dm-d-ageband').value,
    storeys:parseFloat(g('dm-d-storeys').value)||2,
    region:g('dm-d-region').value,
    glazing:g('dm-d-glazing').value,
    ventilation:g('dm-d-ventilation').value,
    wallUpgrade:g('dm-d-wallupgrade').checked,
    roofUpgrade:g('dm-d-roofupgrade').checked,
    extraInsulationHigh:false,
    internalTemp:parseFloat(g('dm-d-internaltemp').value)||21,
    margin:10
  };
}

function demandPickByHpType(peakLossKW,typeTest,count){
  let candidates=calcDb.filter(d=>d.type==='Residential'&&d.cap_max!=null&&typeTest(d.hp_type)&&d.cap_max>=peakLossKW);
  candidates.sort((a,b)=>a.cap_max-b.cap_max);
  let picks=candidates.slice(0,count);
  if(picks.length<count){
    const all=calcDb.filter(d=>d.type==='Residential'&&d.cap_max!=null&&typeTest(d.hp_type));
    all.sort((a,b)=>Math.abs(a.cap_max-peakLossKW)-Math.abs(b.cap_max-peakLossKW));
    const pickedIds=new Set(picks.map(d=>d.id));
    for(const d of all){
      if(picks.length>=count)break;
      if(!pickedIds.has(d.id)){picks.push(d);pickedIds.add(d.id);}
    }
  }
  return picks;
}
function demandRecommendProducts(peakLossKW){
  if(!isFinite(peakLossKW)||peakLossKW<=0)return {ashp:[],gshp:[]};
  const ashp=demandPickByHpType(peakLossKW,t=>!!t&&t.startsWith('ASHP'),6);
  const gshp=demandPickByHpType(peakLossKW,t=>!!t&&t.startsWith('GSHP'),2);
  return {ashp,gshp};
}

function calcCardHTML(d){
  const capLabel=d.cap_min!=null?(d.cap_min+'–'+d.cap_max+' kW'):(d.cap_max+' kW');
  const priceLabel=d.price_min!=null?('£'+Number(d.price_min).toLocaleString()+(d.price_max&&d.price_max!==d.price_min?'–£'+Number(d.price_max).toLocaleString():'')):'';
  return `
    <a class="dm-rec-card" href="${d.url}">
      <div class="dm-rec-card-brand">${d.manufacturer}</div>
      <div class="dm-rec-card-name">${d.model}</div>
      <div class="dm-rec-card-badges">
        <span class="dm-badge">${d.hp_type||''}</span>
        ${d.refrigerant?`<span class="dm-badge dm-badge-ref">${d.refrigerant}</span>`:''}
      </div>
      <div class="dm-rec-card-specs">
        <span>Capacity: <strong>${capLabel}</strong></span>
        ${d.scop!=null?`<span>SCOP: <strong>${d.scop}</strong></span>`:(d.cop!=null?`<span>COP: <strong>${d.cop}</strong></span>`:'')}
      </div>
      ${priceLabel?`<div class="dm-rec-card-price">${priceLabel}</div>`:''}
      <div class="dm-rec-card-link">View full specifications &rarr;</div>
    </a>`;
}

function demandSetMode(mode){
  demandState.mode=mode;
  document.getElementById('dm-tab-simple').classList.toggle('active',mode==='simple');
  document.getElementById('dm-tab-detailed').classList.toggle('active',mode==='detailed');
  document.getElementById('dm-form-simple').style.display=mode==='simple'?'':'none';
  document.getElementById('dm-form-detailed').style.display=mode==='detailed'?'':'none';
  demandRecalc();
}

function demandRecalc(){
  const inp=demandGatherInputs();
  if(!inp.floorArea||inp.floorArea<=0)return;
  const res=demandCompute(inp);
  document.getElementById('dm-peak-value').textContent=res.peakLossKW.toFixed(1)+' kW';
  document.getElementById('dm-peak-sub').textContent='at '+res.region.designTemp+'°C outside / '+inp.internalTemp+'°C inside, incl. '+(inp.margin||0)+'% margin';
  document.getElementById('dm-annual-value').textContent=Math.round(res.annualKWh).toLocaleString()+' kWh';
  document.getElementById('dm-annual-sub').textContent='before solar/internal gains — '+res.region.label+', '+res.region.hdd+' degree days/yr';
  const scop=parseFloat(document.getElementById('dm-scop').value)||3.5;
  const price=parseFloat(document.getElementById('dm-price').value)||25.3;
  const cost=(res.annualKWh/scop)*(price/100);
  document.getElementById('dm-cost-value').textContent='£'+Math.round(cost).toLocaleString();
  document.getElementById('dm-cost-sub').textContent='assuming SCOP '+scop+' · '+price+'p/kWh';
  if(inp.mode==='detailed'){
    document.getElementById('dm-assumptions').innerHTML=
      'Estimated envelope from floor area &amp; storeys — wall '+Math.round(res.geo.netWallArea)+' m² (U='+res.wallU.toFixed(2)+'), glazing '+Math.round(res.geo.windowArea)+' m² (U='+res.glazing.u.toFixed(1)+'), roof '+Math.round(res.geo.roofArea)+' m² (U='+res.roofU.toFixed(2)+'), ground floor '+Math.round(res.geo.groundFloorArea)+' m² (U='+res.floorU.toFixed(2)+'), '+res.ach.toFixed(2)+' air changes/hour. Design external temperature for '+res.region.label+': '+res.region.designTemp+'°C.';
  }
  const recs=demandRecommendProducts(res.peakLossKW);
  const groupsEl=document.getElementById('dm-rec-groups');
  function groupHTML(title,items){
    let cards;
    if(!calcDbLoaded){
      cards='<p class="dm-rec-empty">Loading recommendations…</p>';
    }else if(items.length){
      cards='<div class="dm-rec-grid">'+items.map(calcCardHTML).join('')+'</div>';
    }else{
      cards='<p class="dm-rec-empty">No matching residential '+title.toLowerCase()+' found in the database for this capacity.</p>';
    }
    return '<div class="dm-rec-group-label">'+title+'</div>'+cards;
  }
  groupsEl.innerHTML=groupHTML('Air source (ASHP)',recs.ashp)+groupHTML('Ground source (GSHP)',recs.gshp);
}

let calcDbLoaded=false;
async function loadCalcProducts(){
  try{
    const res=await fetch('/calc-products.json');
    calcDb=await res.json();
  }catch(e){
    calcDb=[];
  }
  calcDbLoaded=true;
  demandRecalc();
}

function initDemandCalc(){
  const ptypeOpts=DEMAND_PROPERTY_TYPES.map(t=>`<option value="${t.id}">${t.label}</option>`).join('');
  const ageOpts=DEMAND_AGE_BANDS.map(a=>`<option value="${a.id}">${a.label}</option>`).join('');
  const regionOpts=DEMAND_REGIONS.map(r=>`<option value="${r.id}">${r.label}</option>`).join('');
  const glazingOpts=DEMAND_GLAZING.map(gl=>`<option value="${gl.id}">${gl.label}</option>`).join('');
  const ventOpts=DEMAND_VENTILATION.map(v=>`<option value="${v.id}">${v.label}</option>`).join('');
  document.getElementById('dm-s-ptype').innerHTML=ptypeOpts;
  document.getElementById('dm-s-ageband').innerHTML=ageOpts;
  document.getElementById('dm-s-ageband').value='1967-1990';
  document.getElementById('dm-d-ptype').innerHTML=ptypeOpts;
  document.getElementById('dm-d-ageband').innerHTML=ageOpts;
  document.getElementById('dm-d-ageband').value='1967-1990';
  document.getElementById('dm-d-region').innerHTML=regionOpts;
  document.getElementById('dm-d-glazing').innerHTML=glazingOpts;
  document.getElementById('dm-d-glazing').value='double-modern';
  document.getElementById('dm-d-ventilation').innerHTML=ventOpts;
  demandRecalc();
  loadCalcProducts();
}

document.addEventListener('DOMContentLoaded',function(){
  if(document.getElementById('dm-s-floorarea'))initDemandCalc();
});
